FROM ubuntu:18.04

RUN apt update && apt install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa && apt update && \
  apt install -y python3-pip

RUN apt install -y git

RUN git clone https://github.com/LeviBarnes/EZCoin

